GET https://entreprise.data.gouv.fr/api/sirene/v1/siren/542065479/
Accept: application/json

{
  "total_results": 59,
  "siege_social": {
    "id": 134121279,
    "siren": "542065479",
    "siret": "54206547900926",
    "nic": "00926",
    "l1_normalisee": "PSA AUTOMOBILES SA",
    "l2_normalisee": "2 10",
    "l3_normalisee": null,
    "l4_normalisee": "2 BOULEVARD DE L EUROPE",
    "l5_normalisee": null,
    "l6_normalisee": "78300 POISSY",
    "l7_normalisee": null,
    "l1_declaree": null,
    "l2_declaree": null,
    "l3_declaree": null,
    "l4_declaree": "2 BOULEVARD DE L EUROPE",
    "l5_declaree": null,
    "l6_declaree": "78300 POISSY",
    "l7_declaree": null,
    "numero_voie": "2",
    "indice_repetition": null,
    "type_voie": "BD",
    "libelle_voie": "DE L EUROPE",
    "code_postal": "78300",
    "cedex": null,
    "region": "11",
    "libelle_region": "Île-de-France",
    "departement": "78",
    "arrondissement": "3",
    "canton": "13",
    "commune": "498",
    "libelle_commune": "POISSY",
    "departement_unite_urbaine": "78",
    "taille_unite_urbaine": "8",
    "numero_unite_urbaine": "00851",
    "etablissement_public_cooperation_intercommunale": "200059889",
    "tranche_commune_detaillee": "43",
    "zone_emploi": "1111",
    "is_siege": "1",
    "enseigne": null,
    "indicateur_champ_publipostage": "A",
    "statut_prospection": null,
    "date_introduction_base_diffusion": "200801",
    "nature_entrepreneur_individuel": null,
    "libelle_nature_entrepreneur_individuel": null,
    "activite_principale": "2910Z",
    "libelle_activite_principale": "Construction de véhicules automobiles",
    "date_validite_activite_principale": null,
    "tranche_effectif_salarie": "51",
    "libelle_tranche_effectif_salarie": null,
    "tranche_effectif_salarie_centaine_pret": null,
    "date_validite_effectif_salarie": "2017",
    "origine_creation": null,
    "date_creation": "20020603",
    "date_debut_activite": "20080101",
    "nature_activite": null,
    "lieu_activite": null,
    "type_magasin": null,
    "is_saisonnier": null,
    "modalite_activite_principale": null,
    "caractere_productif": null,
    "participation_particuliere_production": null,
    "caractere_auxiliaire": null,
    "nom_raison_sociale": "PSA AUTOMOBILES SA",
    "sigle": null,
    "nom": null,
    "prenom": null,
    "civilite": null,
    "numero_rna": null,
    "nic_siege": "00926",
    "region_siege": "11",
    "departement_commune_siege": "78498",
    "email": null,
    "nature_juridique_entreprise": "5599",
    "libelle_nature_juridique_entreprise": "SA à conseil d'administration (s.a.i.)",
    "activite_principale_entreprise": "2910Z",
    "libelle_activite_principale_entreprise": "Construction de véhicules automobiles",
    "date_validite_activite_principale_entreprise": null,
    "activite_principale_registre_metier": null,
    "is_ess": null,
    "date_ess": null,
    "tranche_effectif_salarie_entreprise": "53",
    "libelle_tranche_effectif_salarie_entreprise": null,
    "tranche_effectif_salarie_entreprise_centaine_pret": null,
    "date_validite_effectif_salarie_entreprise": "2017",
    "categorie_entreprise": "GE",
    "date_creation_entreprise": "195401",
    "date_introduction_base_diffusion_entreprise": "201910",
    "indice_monoactivite_entreprise": null,
    "modalite_activite_principale_entreprise": null,
    "caractere_productif_entreprise": null,
    "date_validite_rubrique_niveau_entreprise_esa": null,
    "tranche_chiffre_affaire_entreprise_esa": null,
    "activite_principale_entreprise_esa": null,
    "premiere_activite_secondaire_entreprise_esa": null,
    "deuxieme_activite_secondaire_entreprise_esa": null,
    "troisieme_activite_secondaire_entreprise_esa": null,
    "quatrieme_activite_secondaire_entreprise_esa": null,
    "nature_mise_a_jour": null,
    "indicateur_mise_a_jour_1": null,
    "indicateur_mise_a_jour_2": null,
    "indicateur_mise_a_jour_3": null,
    "date_mise_a_jour": "2020-01-05T20:02:19",
    "created_at": "2020-02-16T13:26:17.000+01:00",
    "updated_at": "2020-02-16T13:26:17.000+01:00",
    "longitude": "2.043907",
    "latitude": "48.933774",
    "geo_score": "0.81",
    "geo_type": "housenumber",
    "geo_adresse": "2 Boulevard de l'Europe 78300 Poissy",
    "geo_id": "ADRNIVX_0000000269415224",
    "geo_ligne": "G",
    "geo_l4": "2 BOULEVARD DE L EUROPE",
    "geo_l5": null
  },
  "other_etablissements_sirets": [
    "54206547900413",
    "54206547901221",
    "54206547900371",
    "54206547901361",
    "54206547900397",
    "54206547900892",
    "54206547900959",
    "54206547900306",
    "54206547900835",
    "54206547900215",
    "54206547901239",
    "54206547900942",
    "54206547900702",
    "54206547901098",
    "54206547900207",
    "54206547900322",
    "54206547901379",
    "54206547901387",
    "54206547901320",
    "54206547900827",
    "54206547900819",
    "54206547900694",
    "54206547901205",
    "54206547900777",
    "54206547900280",
    "54206547901130",
    "54206547900801",
    "54206547901155",
    "54206547900298",
    "54206547901049",
    "54206547901056",
    "54206547900736",
    "54206547900744",
    "54206547900272",
    "54206547901346",
    "54206547900124",
    "54206547901353",
    "54206547900686",
    "54206547900678",
    "54206547901262",
    "54206547901395",
    "54206547901106",
    "54206547900181",
    "54206547901247",
    "54206547901304",
    "54206547900660",
    "54206547901015",
    "54206547901189",
    "54206547900421",
    "54206547900934",
    "54206547900140",
    "54206547900249",
    "54206547901254",
    "54206547901072",
    "54206547900231",
    "54206547900256",
    "54206547900264",
    "54206547900165"
  ],
  "numero_tva_intra": "FR82542065479"
}

###